trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  phpVersion: '8.2'

steps:
- script: |
    sudo update-alternatives --set php /usr/bin/php$(phpVersion)
    php -v
  displayName: 'Switch to PHP $(phpVersion)'

- script: |
    composer install --no-interaction --prefer-dist --optimize-autoloader
  displayName: 'Install Composer Dependencies'

- script: |
    cp .env.example .env
    php artisan key:generate
  displayName: 'Setup Laravel'

- script: |
    php artisan migrate --force
  displayName: 'Run Migrations'

- script: |
    npm install
    npm run build
  displayName: 'Build Frontend Assets'

- script: |
    php artisan test
  displayName: 'Run Tests'
